<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'crawler\\crawlrepository' => '/repository/CrawlRepository.php',
                'crawler\\grep' => '/crawler/Grep.php',
                'crawler\\imagewebcrawler' => '/ImageWebCrawler.php',
                'crawler\\inmemorycrawlrepository' => '/repository/InMemoryCrawlRepository.php',
                'crawler\\mp3webcrawler' => '/Mp3WebCrawler.php',
                'crawler\\notproperlyconfiguredexception' => '/exceptions/NotProperlyConfiguredException.php',
                'crawler\\regexpattern' => '/crawler/RegExPattern.php',
                'crawler\\webcrawler' => '/crawler/WebCrawler.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
